version: '3'

services:
  backend:
    container_name: iwantmusic
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/home/src/app:rw
    ports:
      - "4000:4000"
    command: sh -c 'npm i && npm run start'