
const SPOTIFY_API_VERSION = "v1";
const SPOTIFY_API_URL = "https://api.spotify.com/" + SPOTIFY_API_VERSION;

const SPOTIFY_GENRE_SEED_ROCK = "rock-n-roll";
const SPOTIFY_GENRE_SEED_CLASSIC_MUSIC = "classical";
const SPOTIFY_GENRE_SEED_PARTY = "party";
const SPOTIFY_GENRE_SEED_POP = "pop";

module.exports = {
    SPOTIFY_API_URL,
    SPOTIFY_GENRE_SEED_ROCK,
    SPOTIFY_GENRE_SEED_CLASSIC_MUSIC,
    SPOTIFY_GENRE_SEED_PARTY,
    SPOTIFY_GENRE_SEED_POP
}