name: Node CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Execute npm install
      run: |
        npm ci
        npm run build --if-present
        npm install
    - name: movi file to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MY_SERVER_HOST }}
        username: ${{ secrets.MY_SERVER_USER }}
        password: ${{ secrets.MY_SERVER_PASSWORD }}     
        script: TEST
      env:
        CI: true
