name: Node CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Execute npm install
      run: |
        npm ci
        npm run build --if-present
        npm install
    - name: movi file to server
      run: ./scripts/movie-file.sh  
      env:
        MY_SERVER_HOST: ${{ secrets.MY_SERVER_HOST }}
        MY_SERVER_PASSWORD: ${{ secrets.MY_SERVER_PASSWORD }} 
        CI: true
