name: iWantMusic

on: 
  push:
    branches: 
      - master
    tags-ignore:
      - README.md
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Upload files in server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.MY_SERVER_HOST }}
        username: ${{ secrets.MY_SERVER_USER }}
        password: ${{ secrets.MY_SERVER_PASSWORD }}     
        script: |
          cd /var/www/iwantmusic
          git pull
          docker stop iwantmusic
          docker-compose up --build -d
      env:
        CI: true
